#!/usr/bin/env ruby
# dotcheck
home = File.expand_path(ENV['HOME'])

debug = false

add = ARGV[0] != "--ignore"

IGNORES = File.readlines(File.join(home, "dotfiles", ".ignores")).map do |ignore|
  File.join(home, ignore.chomp)
end

files = []
Dir[File.join(home, "dotfiles", "dotless", "*")].each do |dotless_dir|
  actual_dir = File.join(home, dotless_dir.gsub(File.join(home, "dotfiles", "dotless"), ""), "**/**")
  Dir[actual_dir].each do |file|
    files << File.expand_path(file)
  end
end

Dir[File.join(home, ".*")].each do |home_file|
  next if home_file =~ /\.$/
  files << File.expand_path(home_file)
end

Dir[File.join(home, "dotfiles", "dotted", "*")].each do |dotted_dir|
  next unless File.directory? dotted_dir

  actual_dir = File.join(home, dotted_dir.gsub(File.join(home, "dotfiles", "dotted/"), "."), "**/**")
  Dir[actual_dir].each do |file|
    files << File.expand_path(file)
  end
end

if files.empty?
  puts "USAGE: dotcheck some_path"
  exit 1
end

files.each do |file|
  next if File.symlink? file
  next if IGNORES.include? file

  if File.directory? file
    # puts "[dir] #{file}"
  elsif File.file?(file)
    if add
      puts "dotadd --run #{file}"
    else
      puts "echo #{file.gsub("#{home}/", "")} >> ~/dotfiles/.ignores"
    end
  end
end
